name: StudyBuddy CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      # 1. Get the repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Install Node
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4. Lint code
      - name: Lint code
        run: npm run lint

      # 5. Run tests
      - name: Run tests
        run: npm test
